server:
  port: 10000

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/boxes
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: admin

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    hibernate:
      ddl-auto: update